#!/bin/sh
CONF=/etc/config/qpkg.conf
QPKG_NAME="PowerShell"
QPKG_ROOT=`/sbin/getcfg $QPKG_NAME Install_Path -f ${CONF}`
APACHE_ROOT=`/sbin/getcfg SHARE_DEF defWeb -d Qweb -f /etc/config/def_share.info`
export QNAP_QPKG=$QPKG_NAME
export QPKG_NAME QPKG_ROOT
export SHELL=/bin/sh
export LC_ALL=en_US.UTF-8
export USER=admin
export LANG=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export HOME=$QPKG_ROOT
export TZ=$(/sbin/getcfg System 'Time Zone' -f /etc/config/uLinux.conf)
export TERM=xterm
export HOSTNAME
export POWERSHELL_ROOT=$QPKG_ROOT/powershell

exec $POWERSHELL_ROOT/pwsh "$@"